[package]
name = "df-v-fts"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
datafusion = "46.0.0"
object_store = "0.11.0"
tempfile = "3.19.1"
tokio = { version = "1.44.2", features = ["macros"] }
url = "2.5.4"
vortex-array = "0.31.0"
vortex-buffer = "0.31.0"
vortex-datafusion = "0.31.0"
vortex-error = "0.31.0"
vortex-file = "0.31.0"
