[package]
name = "vfts"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
futures-util = "0.3.31"
tantivy = "0.24.1"
tokio = { version = "1.44.2", features = ["rt-multi-thread", "macros", "fs"] }
vortex-array = { git = "https://github.com/stuhood/vortex/", branch = "stuhood.list-contains-all-elements-but-has-empty-lists" }
vortex-btrblocks = { git = "https://github.com/stuhood/vortex/", branch = "stuhood.list-contains-all-elements-but-has-empty-lists" }
vortex-buffer =  { git = "https://github.com/stuhood/vortex/", branch = "stuhood.list-contains-all-elements-but-has-empty-lists" }
vortex-dtype = { git = "https://github.com/stuhood/vortex/", branch = "stuhood.list-contains-all-elements-but-has-empty-lists" }
vortex-error = { git = "https://github.com/stuhood/vortex/", branch = "stuhood.list-contains-all-elements-but-has-empty-lists" }
vortex-expr = { git = "https://github.com/stuhood/vortex/", branch = "stuhood.list-contains-all-elements-but-has-empty-lists" }
vortex-file = { git = "https://github.com/stuhood/vortex/", branch = "stuhood.list-contains-all-elements-but-has-empty-lists" }
vortex-io = { git = "https://github.com/stuhood/vortex/", branch = "stuhood.list-contains-all-elements-but-has-empty-lists", features = ["tokio"] }
vortex-mask = { git = "https://github.com/stuhood/vortex/", branch = "stuhood.list-contains-all-elements-but-has-empty-lists" }
vortex-scalar = { git = "https://github.com/stuhood/vortex/", branch = "stuhood.list-contains-all-elements-but-has-empty-lists" }
