[package]
name = "df-v-fts"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
futures-util = "0.3.31"
tantivy = "0.24.1"
tokio = { version = "1.44.2", features = ["rt-multi-thread", "macros", "fs"] }
vortex-array = { version = "0.32.0", features = ["test-harness"] }
vortex-btrblocks = "0.32.0"
vortex-buffer =  "0.32.0"
vortex-dtype = "0.32.0"
vortex-error = "0.32.0"
vortex-expr = "0.32.0"
vortex-file = "0.32.0"
vortex-io = { version = "0.32.0", features = ["tokio"] }
vortex-mask = "0.32.0"
