[package]
name = "df-v-fts"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
datafusion = "46.0.0"
tempfile = "3.19.1"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
vortex-array = { path = "../vortex/vortex-array" }
vortex-buffer = { path = "../vortex/vortex-buffer" }
vortex-datafusion = { path = "../vortex/vortex-datafusion" }
vortex-error = { path = "../vortex/vortex-error" }
vortex-file = { path = "../vortex/vortex-file" }
