[package]
name = "df-v-fts"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
vortex-array = { version = "0.32.0", features = ["test-harness"] }
vortex-btrblocks = "0.32.0"
vortex-buffer =  "0.32.0"
vortex-dtype = "0.32.0"
vortex-error = "0.32.0"
vortex-mask = "0.32.0"
